import type { AnalyzeResponse } from '../types'
import { scoreColor } from '../utils/format'

function modelLabel(intelligenceMode: string): string {
  return intelligenceMode === 'random_forest'
    ? 'TravelGuard ML v0.1-demo'
    : 'Rule-based demo engine'
}

export default function SafetyCard({ analysis }: { analysis: AnalyzeResponse }) {
  const overall = analysis.overall_risk
  const isMl = analysis.intelligence_mode === 'random_forest'

  // Key factors come from the worst segment's actual factor reasons.
  const worst = [...analysis.segments].sort((a, b) => b.score - a.score)[0]
  const keyFactors = worst
    ? worst.factors
        .slice()
        .sort((a, b) => b.score - a.score)
        .filter((f) => f.score >= 45)
        .slice(0, 3)
        .map((f) => f.reason)
    : []

  return (
    <section className="glass p-5">
      <div className="flex items-start justify-between">
        <div>
          <h2 className="font-display text-sm font-semibold uppercase tracking-widest text-slate-300">
            Contextual Travel Risk
          </h2>
          <p className="text-[11px] text-slate-500 mt-0.5">
            Model: {modelLabel(analysis.intelligence_mode)}
          </p>
        </div>
        <span
          className="group relative cursor-help text-slate-500 hover:text-cyan-300 text-sm"
          tabIndex={0}
          aria-label="About this score"
        >
          ⓘ
          <span
            className="pointer-events-none absolute right-0 top-6 z-20 w-60 rounded-lg border border-white/10 bg-ink-900/95 p-2.5 text-[11px] text-slate-300 opacity-0 transition-opacity group-hover:opacity-100 group-focus-within:opacity-100"
            role="tooltip"
          >
            This score is a contextual travel-risk indicator, not a probability of an accident.
            {isMl
              ? ' Generated by a RandomForest model trained on synthetic demonstration data.'
              : ' Generated by the deterministic rule engine (ML model not loaded).'}
          </span>
        </span>
      </div>

      <div className="mt-4 flex items-end gap-3">
        <span className="text-4xl font-display font-bold" style={{ color: scoreColor(overall.score) }}>
          {overall.score.toFixed(1)}
        </span>
        <span className="text-sm text-slate-500 mb-1">/ 100</span>
        <span
          className="ml-auto rounded-lg border px-2.5 py-1 text-xs font-bold tracking-wider"
          style={{ color: scoreColor(overall.score), borderColor: `${scoreColor(overall.score)}55`, background: `${scoreColor(overall.score)}14` }}
        >
          {overall.level}
        </span>
      </div>

      {keyFactors.length > 0 && (
        <div className="mt-4">
          <div className="text-[10px] uppercase tracking-widest text-slate-500 mb-1.5">
            Key factors
          </div>
          <ul className="space-y-1">
            {keyFactors.map((f) => (
              <li key={f} className="text-xs text-slate-300 flex items-start gap-1.5">
                <span className="text-amber-300 leading-none mt-0.5">▲</span>
                <span>{f}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </section>
  )
}
